apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  labels:
    app: {name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {name}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {name}
    spec:
      containers:
      - name: kafka
        image: {image}        
        ports:
        - containerPort: 9092
          name: kafka
        env:
        - name: KFK_PATH_CONF
          value: /etc/kafka
        volumeMounts:
        - name: config
          mountPath: /etc/kafka
      volumes:
      - name: config
        configMap: 
          name: {name}-config
